package io.github.arkery.customtickethub.Enums;

public enum Filter_Conditions{
    EMPTY, GETCREATOR, GETINVOLVED, GETASSIGNED ,GETCATEGORY,GETSPECIFICCREATIONDATE,
    GETTICKETSTATUS, GETTICKETPRIORITY, GETTICKETSTATUSANDPRIORITY;
}
