package io.github.arkery.customtickethub;

enum Status_Properties{
    EMPTY, OPEN, ASSIGNED, RESOLVED, CLOSED;
}

enum Priority_Properties{
    EMPTY, LOW, MEDIUM, HIGH, CRITICAL;
}

enum Filter_Conditions{
    EMPTY, GETCREATOR, GETINVOLVED, GETASSIGNED ,GETCATEGORY,GETSPECIFICCREATIONDATE,
    GETTICKETSTATUS, GETTICKETPRIORITY, GETTICKETSTATUSANDPRIORITY;
}