name: TicketHub
version: 0.7
author: arkery
main: io.github.arkery.tickethub.TicketHub
api-version: 1.13
description: Ticket Management Plugin for Spigot based servers

commands:
  th:
    aliases: {ticket, ticketsystem, tickethub}
