name: TicketHub
version: 1.1
author: arkery
main: io.github.arkery.tickethub.TicketHub
api-version: 1.12
description: Ticket Management Plugin for Spigot based servers

commands:
  th:
    aliases: {ticket, ticketsystm, t}
