package io.github.arkery.tickethub.Enums;

public enum Options {
    TICKETID, TICKETTITLE, TICKETCATEGORY, TICKETSTATUS, TICKETPRIORITY,
    TICKETCONTACT, TICKETCONTACTS, TICKETASSIGNEDTO, TICKETDESCRIPTION,
    TICKETCREATOR, TICKETDATECREATED, TICKETDATELASTUPDATED, FILTEREDLIST,
    EMPTY;
}
