package io.github.arkery.tickethub.Enums;

public enum Options {
    ID, TITLE, CATEGORY, STATUS, PRIORITY,
    CONTACT, CONTACTS, ASSIGNEDTO, DESCRIPTION,
    CREATOR, DATECREATED, DATEUPDATED, FILTEREDLIST,
    TICKET, EMPTY, VIEWCOMMENTS, ADDCOMMENT;
}
